# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (every Sunday 00:00)
  schedule: [{cron: "0 0 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/base.svg

          # Options
          user: Roemer
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Zurich
